# Generated by Django 5.1.5 on 2025-03-11 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.order'),
        ),
    ]
