# Generated by Django 5.1.5 on 2025-03-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_order_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
