# Generated by Django 5.1.5 on 2025-03-07 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('expectation', 'В ожидание'), ('done', 'Готово'), ('paid', 'Оплачено')], default='expectation', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('places', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('busy', 'Занято'), ('free', 'Свободно')], default='free', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.table'),
        ),
    ]
