# Generated by Django 5.1.5 on 2025-01-17 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveSmallIntegerField()),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('expectation', 'В ожидание'), ('done', 'Готово'), ('paid', 'Оплачено')], default='expectation', max_length=11)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.dishes')),
            ],
        ),
    ]
