# Generated by Django 5.1.5 on 2025-03-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('expectation', 'В ожидание'), ('done', 'Готово'), ('paid', 'Оплачено'), ('completed', 'Выполнен')], default='expectation', max_length=11),
        ),
    ]
