# Generated by Django 5.1.5 on 2025-01-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_order_items_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='table_number',
        ),
        migrations.AddField(
            model_name='dishes',
            name='order_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='common.order'),
            preserve_default=False,
        ),
    ]
