# Generated by Django 5.1.5 on 2025-03-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
